### ISSUE TITLE
not a superposition in reality

### ISSUE THREAD

**Issue by sneyx123-github** [cmd098/sine-wave-superposition#1]
The superimpose of W1(x,t) and W2(x,t) is only focus of the location in the 1D space but ignores that same location (x) happen at different times(t). So adding them is not reality.
The beating 10 Hz wave has 10 periods at location 40 m but the 20 Hz has 8 periods.
So the W1 figure covers 1s of time and the W2 covers 0.4s of time. 
Adding different time scale is only possible with different media which have different propagation velocities.

**Comment by ssebastianmag** [comment]
Hi,
the principle of superposition states that the resultant displacement at any point is the sum of the displacements due to each  individual wave at that point. Here we calculate the superposition of $W_1(x,t)$ and $W_2(x,t)$ by evaluating both waves at the same time $t$, so the resulting wave $W_R(x,t) = W_1(x,t) + W_2(x,t)$ accurately represents the superposition.

Although a $10 Hz$ wave completes 10 periods in 1 second and a $20 Hz$ wave completes 20 periods, we evaluate both waves at the same $t$. This is a standard approach in wave physics to ensure valid superposition by summing instantaneous displacements at each time step, thus accounting for their different periods.

I hope this clarifies the approach and validity of the model. Thank you.

Regards,
Sebastian

**Comment by sneyx123-github** [comment]
Hi,

The propagation velocity of a wave is equal to the product of its wavelength and its frequency, expressed by the formula v = λ f 

For W1 the propagation velocity of the medium is:
 4 m * 10 Hz = 40 m/s 
and for W2 the propagation velocity of the medium is: 
5 m * 20 Hz = 100 m/s.

These parameter implies different media for each wave. 

Parameter for the model without contradictionary propagation velocities could be:
W1: λ=4 m and f = 20 Hz; v=80 m/s 
W2: λ=5 m and f =16 Hz ; v=80 m/s

There are of course time travelers who are in different spaces at the same time (superposition in space) and other time travelers who are at the same space at different times (superposition in time). It is best if the space and time parameters can be selected together.

Regards,
Simon

**Comment by ssebastianmag** [comment]
Hi, I can see your point now Simon, thank you

Indeed by ensuring that the product is constant for both waves, we can maintain the same propagation velocity where $v = \lambda_1 f_1 = \lambda_2 f_2$, that would make the model "theoretically" sound for a single medium.

I made this 2 years ago, so I don't remember why I decided to dismiss this state, probably due to visualization constraints with matplotlib, at least that's what comes to mind as of now, I will try using this approach to see how it looks in a plot.

Thank you again!
